//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TBKH_AUTHOR
{
    public int AUTHOR_KY { get; set; }
    public string AUTHOR_NAME { get; set; }
    public Nullable<System.DateTime> AUTHOR_BIRTHDAY { get; set; }
    public string AUTHOR_SEX_CODE { get; set; }
    public string AUTHOR_SEX_DESC { get; set; }
    public string AUTHOR_HOMETOWN { get; set; }
    public string AUTHOR_OPUS { get; set; }
    public string AUTHOR_DESC { get; set; }
    public Nullable<System.DateTime> AUTHOR_ADD_TIME { get; set; }
    public Nullable<int> AUTHOR_STATUS_CODE { get; set; }
    public string AUTHOR_STATUS_DESC { get; set; }
    public string AUTHOR_WORKS { get; set; }
    public string AUTHOR_BAIKE_URL { get; set; }
    public string AUTHOR_FRIEND { get; set; }
    public string AUTHOR_IMG { get; set; }
    public Nullable<int> FLOWER_NUM { get; set; }
}

public partial class TBKH_VIDEO_INFO
{
    public int VIDEO_KY { get; set; }
    public Nullable<int> VIDEO_AUTHOR_KY { get; set; }
    public string VIDEO_NAME { get; set; }
    public string VIDEO_TIME { get; set; }
    public string VIDEO_IMG { get; set; }
    public Nullable<int> VODEO_VIEW_COUNT { get; set; }
    public string VIDEO_DESC { get; set; }
    public string VIDEO_SHARE_URL { get; set; }
    public Nullable<int> VIDEO_GOOD_CLICK { get; set; }
    public Nullable<int> VIDEO_BAD_CLICK { get; set; }
    public Nullable<System.DateTime> VIDEO_ADD_TIME { get; set; }
    public Nullable<int> VIDEO_STATUS_CODE { get; set; }
    public string VIDEO_STATUS_DESC { get; set; }
    public string VIDEO_PERFORMER { get; set; }
    public string VIDEO_FORM { get; set; }
    public Nullable<int> VIDEO_HEIGHT { get; set; }
    public Nullable<int> VIDEO_WIDTH { get; set; }
}
